### ISSUE TITLE
HA error connecting to matrix via host / IP connection

### ISSUE THREAD

**Issue by xeospeed** [koolsb/pyblackbird#3]
Hi @koolsb,

I'm trying to connect my Blackbird 8x8 HDBaseT Matrix Switcher and seem to be having an issue integrating it with Home Assistant. I'm currently running Hassio 0.103.6. I'm able to access and log into the matrix via the web interface and pinging the matrix, it responds without issue.

Here's the error being thrown in my home assistant logs:

`Error while setting up platform blackbird
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/blackbird/media_player.py", line 87, in setup_platform
    blackbird = get_blackbird(host, False)
  File "/usr/local/lib/python3.7/site-packages/pyblackbird/__init__.py", line 263, in get_blackbird
    return BlackbirdSync(url)
  File "/usr/local/lib/python3.7/site-packages/pyblackbird/__init__.py", line 176, in __init__
    self.socket.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused`

I greatly appreciate you creating this component! In fact, I switched from an AVIshop matrix to this one just for the Home Assistant integration.

Regards,
Matthew

P.S. Unsure if the exact model of Blackbird 8x8 matrix matters, but here's the manual to my specific model. Thanks again. [https://downloads.monoprice.com/files/manuals/27842_Manual_180419.pdf](url)

**Comment by ragaimeena** [comment]
I have the same model and the same issue
can someone please help or advise if this is compatible with this model #27842
thank you
