### ISSUE TITLE
socket.timeout when trying to connect to my blackbird 4x4 HDBaseT matrix

### ISSUE THREAD

**Issue by thomasvs** [koolsb/pyblackbird#4]
Both in homeassistant's log and when setting up python3 and pyblackbird from scratch, I get:

python3) (b:master) thomasvs@thomasvsl7:~/dev/ext/pyblackbird$ python bb.py 
<module 'serial' from '/home/thomasvs/dev/ext/pyblackbird/python3/lib/python3.7/site-packages/serial/__init__.py'>
Traceback (most recent call last):
  File "bb.py", line 10, in <module>
    print('System Lock is {}'.format('On' if blackbird.lock_status() else 'Off'))
  File "/home/thomasvs/dev/ext/pyblackbird/pyblackbird/__init__.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "/home/thomasvs/dev/ext/pyblackbird/pyblackbird/__init__.py", line 261, in lock_status
    return LockStatus.from_string(self._process_request(_format_lock_status()))
  File "/home/thomasvs/dev/ext/pyblackbird/pyblackbird/__init__.py", line 220, in _process_request
    data = self.socket.recv(SOCKET_RECV)
socket.timeout: timed out

**Comment by shinyshoes16** [comment]
What model of matrix are you using?  I'm currently trying to get a 24180 working and have to modify some code to get it to go.  I'll be submitting a pull request soon to get it to work for mine.

**Comment by rb4774** [comment]
Having the same issue.  I have a model 24180.  The version of firmware reported by the device is v1.0.1.
From what I can determine, the commands are not the same for all versions.  The commands that I can get to work by sending them with Packet Sender are from [this ](https://downloads.monoprice.com/files/manuals/24180_Manual_201014.pdf) user manual. 
I tried debugging the current pyblackbird code.  The commands it tries to use are for the HDBaseT 8x8 Matrix (Model 21819) but the 24180 had different commands.  And some do not even exist.  For example the 21819 allow you to query a single output.  But the 24180 only let's you query all outputs at once.
I can provide more details if anyone is able to update the code.  I can take a stab at it myself, but am new to home assistant and since the commands are not one-to-one for the models I think it will be a little bit complex.

**Comment by shinyshoes16** [comment]
The 24180 I have is an older version than yours and has slightly different commands.  You can view my modifications [here](https://github.com/koolsb/pyblackbird/pull/5) and possibly modify it again to fit your needs.  You can then run it as a custom_component in Home Assistant. 

I wouldn't hold your breath on getting your changes merged into this integration though.  I submitted my request almost 4 years ago and the owner @koolsb has never responded or even acknowledged my request existed, despite me trying to contact him many different ways.
